import { GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS } from './notificationEventIds';
import type { NotificacionItem } from './notifications.types';

/**
 * Datos de demostración: avisos operativos y notificaciones del cliente interno (líder / invitado)
 * bajo la pestaña «Gestión de candidatos», con agrupación simulada de lote.
 */
export const MOCK_NOTIFICACIONES: NotificacionItem[] = [
  {
    id: 'n-guest-stage-1',
    kind: 'client-internal-candidates',
    vacancyId: 'v-02',
    vacancyTitle: 'Desarrollador Frontend React Senior',
    secondsAgo: 60 * 2,
    read: false,
    priority: 'high',
    clientInternal: {
      eventId: GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS.STAGE_MOVE,
      leaderName: 'Laura Méndez',
      candidateName: 'Angie Paola Bolaños Díaz',
      targetStageName: 'Entrevista técnica',
      historyEntryId: 'hu5-01',
    },
  },
  {
    id: 'n-guest-comment-1',
    kind: 'client-internal-candidates',
    vacancyId: 'v-02',
    vacancyTitle: 'Desarrollador Frontend React Senior',
    secondsAgo: 60 * 8,
    read: false,
    clientInternal: {
      eventId: GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS.COMMENT,
      leaderName: 'Patricia Gómez',
      candidateName: 'Dominga Luz Velasquez Monsalve',
      historyEntryId: 'hu5-01',
    },
  },
  {
    id: 'n-guest-rating-bulk-1',
    kind: 'client-internal-candidates',
    vacancyId: 'v-04',
    vacancyTitle: 'Diseñador UX/UI',
    secondsAgo: 60 * 20,
    read: false,
    clientInternal: {
      eventId: GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS.RATING,
      leaderName: 'Ricardo Mora',
      candidateName: 'Candidato 1',
      stars: 5,
      bulkAggregationId: 'bulk-ratings-demo-1',
      historyEntryId: 'hu5-02',
    },
  },
  {
    id: 'n-guest-rating-bulk-2',
    kind: 'client-internal-candidates',
    vacancyId: 'v-04',
    vacancyTitle: 'Diseñador UX/UI',
    secondsAgo: 60 * 21,
    read: false,
    clientInternal: {
      eventId: GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS.RATING,
      leaderName: 'Ricardo Mora',
      candidateName: 'Candidato 2',
      stars: 5,
      bulkAggregationId: 'bulk-ratings-demo-1',
      historyEntryId: 'hu5-02',
    },
  },
  {
    id: 'n-guest-rating-bulk-3',
    kind: 'client-internal-candidates',
    vacancyId: 'v-04',
    vacancyTitle: 'Diseñador UX/UI',
    secondsAgo: 60 * 22,
    read: false,
    clientInternal: {
      eventId: GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS.RATING,
      leaderName: 'Ricardo Mora',
      candidateName: 'Candidato 3',
      stars: 4,
      bulkAggregationId: 'bulk-ratings-demo-1',
      historyEntryId: 'hu5-02',
    },
  },
  {
    id: 'n-guest-rating-single',
    kind: 'client-internal-candidates',
    vacancyId: 'v-03',
    vacancyTitle: 'Analista de Datos Junior',
    secondsAgo: 60 * 45,
    read: true,
    clientInternal: {
      eventId: GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS.RATING,
      leaderName: 'Andrea Gómez',
      candidateName: 'Beatriz Castañón Cuervo',
      stars: 4,
      historyEntryId: 'hu5-02',
    },
  },
  {
    id: 'n-guest-stage-bulk-1',
    kind: 'client-internal-candidates',
    vacancyId: 'v-05',
    vacancyTitle: 'Ingeniero DevOps',
    secondsAgo: 60 * 55,
    read: false,
    priority: 'high',
    clientInternal: {
      eventId: GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS.STAGE_MOVE,
      leaderName: 'Miguel Torres',
      candidateName: 'Perfil A',
      targetStageName: 'Validación final',
      bulkAggregationId: 'bulk-stage-demo-1',
      historyEntryId: 'hu5-01',
    },
  },
  {
    id: 'n-guest-stage-bulk-2',
    kind: 'client-internal-candidates',
    vacancyId: 'v-05',
    vacancyTitle: 'Ingeniero DevOps',
    secondsAgo: 60 * 56,
    read: false,
    priority: 'high',
    clientInternal: {
      eventId: GUEST_CANDIDATE_NOTIFICATION_EVENT_IDS.STAGE_MOVE,
      leaderName: 'Miguel Torres',
      candidateName: 'Perfil B',
      targetStageName: 'Validación final',
      bulkAggregationId: 'bulk-stage-demo-1',
      historyEntryId: 'hu5-01',
    },
  },
  {
    id: 'n-legacy-decision',
    kind: 'client-internal-candidates',
    vacancyId: 'v-02',
    vacancyTitle: 'Desarrollador Frontend React Senior',
    secondsAgo: 60 * 200,
    read: true,
    clientInternal: {
      actionLabel: 'Decisión',
      leaderName: 'Laura Méndez',
      candidateName: 'Dominga Luz Velasquez Monsalve',
      isQuickDecision: true,
      historyEntryId: 'hu5-03',
    },
  },
  {
    id: 'n-exp-1',
    kind: 'vacancy-expiring',
    vacancyId: 'v-06',
    vacancyTitle: 'Líder Técnico Backend Node.js',
    secondsAgo: 60 * 15,
    read: false,
    metaLine: 'Término indefinido | Creada: 2026-04-28 | Expira: 2026-07-28',
    headline:
      'La vacante @analista está a punto de expirar. Actualice la fecha de publicación para seguir recibiendo postulaciones.',
  },
  {
    id: 'n-st-1',
    kind: 'vacancy-status',
    vacancyId: 'v-05',
    vacancyTitle: 'Ingeniero DevOps',
    secondsAgo: 60 * 40,
    read: false,
    metaLine: 'Por proyecto | Creada: 2026-04-15',
    headline: 'La vacante cambió de estado a Publicada.',
  },
  {
    id: 'n-sol-1',
    kind: 'solicitud-vacante',
    vacancyId: 'v-07',
    vacancyTitle: 'Product Manager',
    secondsAgo: 60 * 180,
    read: true,
    headline: 'Tiene una nueva solicitud de publicación de vacante pendiente de revisión.',
  },
];
